from dotenv import load_dotenv, find_dotenv

load_dotenv()


configfile: "config/qa/occurrence.yml"
configfile: "config/llm/gpt-3.5-turbo-0125.yml"


include: "qa.smk"


rule all:
    input:
        "results/responses.tsv",
