random_seed: 69847
recordset: hash://md5/8f0594be7f88e4fc7b30c0854e7ca029
nomer_alignment_report_url: https://raw.githubusercontent.com/mielliott/idigbio-sample-alignment/main/alignment-report/names-aligned.tsv
qa:
  defaults:
    args:
      - --model-category gpt
      - --model-name gpt-3.5-turbo-0125
  occurrence:
    input: results/idigbio-sample/input/all.tsv
    query_limit: 15
    batch_size: 5
  taxonomy:
    input: results/idigbio-sample/input/taxonomy-qa.tsv
    query_limit: 15
    batch_size: 5
results:
  notebook: process-occ-gpt.py.ipynb