qa_input: resources/test-occurrence-qa.tsv
qa_query_limit: 0
qa_batch_size: 5
qa_query_templates:
  - Does {genus} {specificepithet} naturally occur in {county}, {stateprovince}, {country}?
  - Can species {genus} {specificepithet} be found in {county}, {stateprovince}, {country}?
  - Is it possible to encounter species {genus} {specificepithet} in {county}, {stateprovince}, {country}?
  - Is there a presence of species {genus} {specificepithet} within {county}, {stateprovince}, {country}?
  - Does {county}, {stateprovince}, {country} harbor species {genus} {specificepithet}?
  - Is species {genus} {specificepithet} present in {county}, {stateprovince}, {country}?
  - Can one observe species {genus} {specificepithet} in {county}, {stateprovince}, {country}?
qa_query_suffix: Only respond yes or no.
qa_command_env: $ROOT/scripts/nlp/env.yml
qa_command: python3 $ROOT/scripts/nlp/main.py
qa_command_args:
  max_tokens: 1
  timeout: 10
  scores: first_token
