test_name: idigbio-sample
job_name: llama2-7b
random_seed: 69847
recordset: hash://md5/8f0594be7f88e4fc7b30c0854e7ca029
nomer_alignment_report_url: https://raw.githubusercontent.com/mielliott/idigbio-sample-alignment/main/alignment-report/names-aligned.tsv
qa:
  occurrence:
    input: results/idigbio-sample/input/all-shuffled-69847.tsv
    shuffle: true
    query_limit: 40000
    batch_size: 100
    query_suffix: "Only respond yes or no.\n\nThe answer is"
  taxonomy:
    input: results/idigbio-sample/input/taxonomy-qa.tsv
    shuffle: false
    query_limit: 0
    batch_size: 100
    query_suffix: "Only say its scientific name.\n\n{taxon} belongs to the {object_rank} called"
results:
  notebook: results-llama2.py.ipynb
