llm: llama-3.2-1b-instruct
prep_command: cat
command: python3 $ROOT/scripts/nlp/main.py
command_env: $ROOT/scripts/nlp/env.yml
input: resources/occurrence-qa.tsv
output_dir: results/occurrence-qa
args: # The arguments to `command`
  - --max-tokens 1
  - --num-responses 1
  - --timeout 10
  - --model-category "llama"
  - --model-name "llama-3.2-1b-instruct"
shuffle: false
batch_size: 100
query_limit: 0 # Set to 0 to run all queries, otherwise only run this many (x the number of query templates)
query_fields:
  - kingdom
  - phylum
  - family
  - genus
  - specificepithet
  - country
  - stateprovince
  - county
query_templates:
  - Does {genus} {specificepithet} naturally occur in {county}, {stateprovince}, {country}?
  - Can species {genus} {specificepithet} be found in {county}, {stateprovince}, {country}?
query_suffix: Only respond yes or no.
