configfile: "config.yml"

LLM = config["llm"]

PRESENCE_IN = "resources/presence.tsv"
ABSENCE_IN = "resources/absence.tsv"

PRESENCE_OUT = f"results/{LLM}/presence.tsv"
ABSENCE_OUT = f"results/{LLM}/absence.tsv"

include: "rules/make-presence-tsv.smk"
include: "rules/make-absence-tsv.smk"
include: "rules/qa.smk"

rule all:
    input:
        "all.done"

rule analyze_results:
    input:
        presence=PRESENCE_OUT,
        absence=ABSENCE_OUT,
        absence_valid="results/absence-valid.tsv"
    output:
        "all.done"
    conda:
        "envs/analysis.yml"
    notebook:
        "notebooks/results.py.ipynb"
