import os
from dotenv import load_dotenv, find_dotenv

load_dotenv()

outputs = os.path.join(config["output_dir"], config["llm"])

print(f"out: {outputs}/responses.tsv")


include: "rules/qa.smk"


rule all:
    input:
        f"{outputs}/responses.tsv",
    output:
        f"{outputs}/all-done",
    shell:
        "touch {output}"
