configfile: "config/defaults.yml"

LLM = config["llm"]

PRESENCE_IN_UNFILTERED = "results/input/presence-unfiltered.tsv"
PRESENCE_IN = "results/input/presence.tsv"
ABSENCE_IN = "results/input/absence.tsv"
ALL_IN = "results/input/all.tsv"
ALL_IN_SHUFFLED = "results/input/all-shuffled.tsv"
TRAIN_TEST_SPLIT = "results/input/train_test_split.tsv"

ABSENCE_VALID = "results/input/absence-valid.tsv"

PRESENCE_OUT = f"results/{LLM}/presence.tsv"
ABSENCE_OUT = f"results/{LLM}/absence.tsv"
ALL_OUT = f"results/{LLM}/all.tsv"
ALL_OUT_SHUFFLED = f"results/{LLM}/all-shuffled.tsv"
NOTEBOOK_OUT = f"results/{LLM}/results.py.ipynb"

include: "rules/get-records.smk"
include: "rules/make-presence-tsv.smk"
include: "rules/make-absence-tsv.smk"
include: "rules/combine-tsv.smk"
include: "rules/qa.smk"
include: "rules/qa-analysis.smk"

rule all:
    input:
        NOTEBOOK_OUT
